### ISSUE TITLE
Question about postnet during inference time

### ISSUE THREAD

**Issue by joannahong** [soobinseo/Transformer-TTS#36]
Thanks for great work! I have a question in synthesis.py which is little bit unclear for me.
In the original Tacotron2, a stacked mel_pred generated from each step(max step=args.max_len) goes into a postnet which creates a post_mel_pred. 
But in synthesis.py, each mel_pred goes into postnet in every step, and the output postnet_pred get concatenated with previous mel_input. (Here, I am talking about postconvnet from MelDecoder.)
I am thinking that the generating scheme of transformer is little bit different from the Tacotron2 (I haven't looked up the original Tensorflow version of Transformer TTS, sorry for inconvenience :( ), so I want to ask that is there any reason that the transformer is designed like that? Or, are both schemes actually the same thing?
Thank you again for such a great repository!

**Comment by soobinseo** [comment]
제가 한글이 설명하기 편하여 한국분이신거같아 한글로 답변 드리겠습니다. (If you are uncomfortable with Korean, I will reply again in English. ^^)
![스크린샷 2021-01-14 오후 11 30 57](https://user-images.githubusercontent.com/18044285/104604569-d740f480-56c0-11eb-81e8-78a0ea7d302d.png)
이 코드를 보시면 for loop안에서 전체 mel spectrogram을 다 생성 후에 post convnet에 concat된 mel이 한번에 입력값으로 들어갑니다. (제가 joanna님의 질문을 잘못 이해했는지 모르겠지만 synthesis.py에는 maxlen까지 mel이 생성된 후에 postnet에 stack되어 입력으로 들어가는 코드가 맞습니다.)
이유는, mel decoder와 postnet이 완전히 독립적으로 학습되었고, 특히 postnet은 학습시에 완전한 mel spectrogram을 입력값으로 받기 때문에 inference시 mel이 스텝마다 입력으로 주어진다면 각 스텝마다의 에러가 중첩되어 더 안좋은 결과가 나타날 수 있습니다. 따라서 스텝마다의 에러 중첩을 최대한 줄이기 위해 mel을 먼저 스텝마다 생성후에, 한번에 postnet에 들어가게 코드를 짰습니다.

두가지 방법(매 스텝마다 끝까지 inference / stacked mel 후 postnet)은 확연히 다르고, 학습을 어떻게했느냐에 따라 inference style도 달라지겠죠.
postnet까지 end-to-end로 학습하였다면 1스텝마다 postnet 끝까지 inference해도 되겠지만 이 방법으로 훈련 시에 학습이 잘 진행되지 않았습니다.

충분한 답변이 되었는지 모르겠네요. 혹시 추가로 질문있으시면 이슈로 또 남겨주세요! ^^

**Comment by soobinseo** [comment]
제가 한글이 설명하기 편하여 한국분이신거같아 한글로 답변 드리겠습니다. (If you are uncomfortable with Korean, I will reply again in English. ^^)
![스크린샷 2021-01-14 오후 11 30 57](https://user-images.githubusercontent.com/18044285/104607561-4b30cc00-56c4-11eb-9d95-d7a52f466edb.png)

이전 답글에서의 답변에서 mel --> linear로 변환하는 postnet과 착각했네요,,
다시 생각해보니 joanna님께서 지적해 주신 부분이 맞습니다. 정말 좋은 지적 감사합니다. 코드가 잘못되었네요. post convnet을 따로 빼고 한번에 stack해서 inference하는 것이 error를 중첩하지 않는데 더 좋을 것 같습니다.

두가지는 확실히 다를 것 같습니다. 현재 postnet conv의 kernel size를 보니 5로 지정되어있고, 이 경우 매 스텝마다 생성하면 초반에 제대로된 주위 정보들을 보지 못한채 생성이 될테고 스텝이 길어질수록 에러가 더 많이 전파되겠죠. 

시간이 되면 수정하도록 하겠습니다 감사합니다!
혹시 추가로 질문이나 수정사항 발견하셨다면 이슈로 또 남겨주세요! ^^

**Comment by joannahong** [comment]
감사드립니다 👍 !!

**Comment by soobinseo** [comment]
mel 생성후 postnet에 들어가도록 업데이트 했습니다. 감사합니다!! 
다만, 생성된 샘플들을 들어보니 크게 차이는 없는거같네요 ㅜ 학습 attention matrix가 가장 중요할 것 같습니다.

**Comment by joannahong** [comment]
혹시 추가로 outputs_per_step>1 케이스에 대해서는 구현이 안되어있는건지 여쭤보고 싶습니다!

**Comment by soobinseo** [comment]
이 레포에는 구현이 안되어있구요,
https://github.com/soobinseo/Tacotron-pytorch/blob/master/network.py#L65
여길 참고하시면 됩니다. 다만 코드가 엄청 옛날버전이라 보시기 좀 불편하실수도 있어요,, ㅎㅎ
