### ISSUE TITLE
Caught StopIteration in replica 1 on device 1 error

### ISSUE THREAD

**Issue by aizaz-hussain** [soobinseo/Transformer-TTS#39]
I have successfully prepared the data but when I run the python script **train_transformer.py** I get the following error _**StopIteration: Caught StopIteration in replica 1 on device 1.**_ How can I resolve this one?

**Comment by B-1368** [comment]
Just got the exactly the same question and solved it. You may need to downgrade pytorch to 1.4.0 and torchvision to 0.5.0

Ref: https://github.com/huggingface/transformers/issues/4189#issuecomment-625292577
