### ISSUE TITLE
Text to Phoneme Converter

### ISSUE THREAD

**Issue by TakoYuxin** [soobinseo/Transformer-TTS#7]
From the structure diagram, I saw a text to phoneme converter in the preprocessing steps. However, I wasn't able to find the corresponding code anywhere. It might just be me being stupid and not careful enough so could anyone tell me which part of the code is functioning as a text to phoneme converter?

**Comment by soobinseo** [comment]
Oh, I forgot to mention that I did not use the text to phoneme module.
I just used pure text, and generated wav. (well, some preprocessing was applied, from keithito's code)
Thank you.

**Comment by TakoYuxin** [comment]
> Oh, I forgot to mention that I did not use the text to phoneme module.
> I just used pure text, and generated wav. (well, some preprocessing was applied, from keithito's code)
> Thank you.

Thank you for answering! I am also trying to implement the Neural Speech Synthesis with Transformer Network paper and your code is really helpful! I think cmudict.py has something useful for converting text to phoneme so I might continue looking into that and see if I could add a text to phoneme converter somehow.
